### ISSUE TITLE
Significant fps drops in locations with a lot of pets

### ISSUE THREAD

**Issue by YvesW** [microtavor5/PetInfoPlugin#27]
Steps to reproduce:
1. Go to a T9 shooting star
2. Wait till all the people have gathered
3. Mouse over the viewport
4. FPS tanks

**Comment by microtavor5** [comment]
The FPS drop happens when you mouse over a tile with many pets on it, not just when there's a lot of pets around, correct?
If that's the case it might be related to adding the menu entries, thank you for bringing this to my attention

**Comment by YvesW** [comment]
> The FPS drop happens when you mouse over a tile with many pets on it, not just when there's a lot of pets around, correct? If that's the case it might be related to adding the menu entries, thank you for bringing this to my attention

Not really. It happens when you hover over the viewport. It does not happen if you hover over the minimap/invent or open a right-click menu, and it does not happen with the plugin turned off. I've quickly made a video with OBS:
https://files.catbox.moe/dqkndu.mkv

It's probably due to players rendering as null due to the amount of players. I've attached the (semi-)relevant part of the logs (although some other plugins also do show up in there ofc). You can see me world hopping (FlippingUtilities) and I arrive at the star at approx 3:48.

```2023-09-24 03:45:36 CEST [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2023-09-24 03:48:01 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.util.Text.sanitize(Text.java:191)
	at com.example.VengTrackerOverlay.render(VengTrackerOverlay.java:47)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:485)
	at jt.bf(jt.java:18816)
	at qy.jw(qy.java:4971)
	at jh.lb(jh.java:10739)
	at jh.lb(jh.java:10770)
	at jh.lb(jh.java:10770)
	at jh.lb(jh.java:10770)
	at pb.lz(pb.java:10634)
	at client.kt(client.java:4675)
	at client.bp(client.java:1130)
	at bb.bd(bb.java:388)
	at bb.run(bb.java:337)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-24 03:48:01 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at net.runelite.client.util.Text.removeFormattingTags(Text.java:96)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onSpawned(EventHandler.java:341)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onActorSpawned(EventHandler.java:289)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onPlayerSpawned(EventHandler.java:282)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:209)
	at client.ia(client.java:15459)
	at client.bt(client.java)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-24 03:48:01 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.util.Text.toJagexName(Text.java:133)
	at com.runewatch.RuneWatchPlugin.alertPlayerWarning(RuneWatchPlugin.java:531)
	at com.runewatch.RuneWatchPlugin.onPlayerSpawned(RuneWatchPlugin.java:251)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:209)
	at client.ia(client.java:15459)
	at client.bt(client.java)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-24 03:48:01 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:48:01 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at net.runelite.client.util.Text.removeFormattingTags(Text.java:96)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onSpawned(EventHandler.java:341)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onActorDespawned(EventHandler.java:292)
	at com.adamk33n3r.runelite.watchdog.EventHandler.onPlayerDespawned(EventHandler.java:286)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at client.kh(client.java:29933)
	at ky.ao(ky.java:462)
	at oc.ak(ox.java:376)
	at dq.al(dq.java:74)
	at client.kq(client.java:19664)
	at client.gw(client.java:3098)
	at client.bt(client.java:1124)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-24 03:48:10 CEST [Client] INFO  client-patch - cache animationCache thrashing, enlarging to 128 entries
2023-09-24 03:48:17 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:48:17 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:48:30 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:48:30 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:48:44 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:48:44 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:01 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:01 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:15 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:15 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:26 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:26 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:37 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:37 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:48 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:48 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:49:59 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:49:59 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:50:05 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.util.Text.sanitize(Text.java:191)
	at com.example.VengTrackerPlugin.onMenuEntryAdded(VengTrackerPlugin.java:93)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at client.ok(client.java:48951)
	at iv.lk(iv.java:10306)
	at fp.lc(fp.java:10292)
	at nh.ld(nh.java:31779)
	at eg.lo(cx.java:10427)
	at eg.mz(cx.java:11538)
	at eg.mz(cx.java:11951)
	at eg.mz(cx.java:11951)
	at eg.mz(cx.java:11951)
	at tn.mf(tx.java:11462)
	at client.gw(client.java:3391)
	at client.bt(client.java:1124)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-24 03:50:05 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:50:05 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
ve: null
	at oc.al(ox.java:104)
	at rn.br(rn.java:52)
	at rn.bm(rn.java:45)
	at ci.ae(ci.java:220)
	at dj.ao(dj.java:198)
	at dj.ak(dj.java:188)
	at dj.isFriend(dj.java)
	at com.guestindicators.GuestIndicatorsPlugin.getDecorations(GuestIndicatorsPlugin.java:185)
	at com.guestindicators.GuestIndicatorsPlugin.onClientTick(GuestIndicatorsPlugin.java:155)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:193)
	at client.pk(client.java:11788)
	at client.gw(client.java:3392)
	at client.bt(client.java:1124)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at rn.br(rn.java:51)
	... 16 common frames omitted
2023-09-24 03:50:10 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:50:10 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:50:26 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:50:26 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:50:54 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:50:54 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:51:14 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:51:14 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:51:28 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:51:28 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:51:40 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:51:40 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:51:45 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:51:45 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:51:45 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:51:45 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:51:46 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:51:46 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:51:46 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:51:46 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:51:52 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:51:52 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:04 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:04 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:17 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:17 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:27 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:27 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:35 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:35 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:44 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:44 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:52:52 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:52:52 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:00 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:00 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:08 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:08 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:16 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:16 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:24 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:24 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:33 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:33 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:41 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:41 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:50 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:50 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-09-24 03:53:56 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2023-09-24 03:53:58 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:53:58 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:54:07 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:54:07 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2023-09-24 03:54:15 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2023-09-24 03:54:15 CEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
```

**Comment by Hannah-GBS** [comment]
Experiencing the exact same behaviour. Mousing over the game window (not invent/map UI) drops like 30 FPS when many pets are in the scene.

**Comment by microtavor5** [comment]
Ahh ok, then in that case it is likely that the drop is being caused by the check to see if there are any pets under the cursor, since they do not natively have a list of menu options to edit. I was worried this would be a possibility.
I'll look into what I can do to speed things up, but with my current way of doing things there is no way to guarantee no fps drop given a sufficient number of pets, so I'll probably need to change things up to find a true solution, but in the meanwhile I'll look into a stop gap measure.
My immediate thoughts for a stopgap to allow the plugin to not be an active burden while in that scenario would be to either
 a. Limit the number of pets checked against, maybe see if there is a way to guarantee that the top pet is included?
 b. When there are a lot of pets move the calculations to be handled when the player right clicks. This will cause a slight slow down on the right click, and there will be a visible lag between when the menu appears and when the pet menu entries appear in the menu itself.

Honestly the pet menu entries might be more annoying than useful in this kind of scenario, if a significant number of pets end up on the same tile.

Anything that either of you would prefer to see in the meantime?

**Comment by YvesW** [comment]
I did a very brief test, but commenting out the following part of ``getPetsUnderCursor()`` does indeed fix the FPS drops.

```
/*for (NPC p : pets) {
	if (isClickable(p, mouseCanvasPosition)) {
		list.add(p);
	}
}*/
```
Try to optimize that code if possible. Disclaimer: I have not looked at the rest of your codebase, so not sure how realistic that is or if there's just a better way to implement this.

Option b seems rather annoying, so I'd go with option a indeed.

**Comment by microtavor5** [comment]
Ok, thank you for investigating this. I'll look into general optimizations as well as anything I can do more specifically
These things always find a way cropping up right before I travel international 😅
Do you know roughly how many pets were around at the time? If not, don't go out of your way to try and find out for me I'm just wondering at the scale, I can find out myself soon enough

**Comment by microtavor5** [comment]
So it looks like on _my_ machine the problem begins at around 80 pets, and a T9 can get over 100 pets hanging around. That being said, there were times when I had no issues what so ever with over 100 pets, so there might be something else going on as well.
When I added a limit of 50 pets checked I had no issues, so I think for now I'll add a changeable cap in the settings, maybe default it to 45. This lets people adjust the temporary fix to suit their machine.

I'm still going to look into better optimizations and maybe being able to have the pets have a menu entry list for themselves like other NPCs do, so that I don't need to add them every tick (to avoid the visible menu delay), and it will prevent the problem from scaling with the number of pets.

**Comment by microtavor5** [comment]
So I only just now managed to actually make the pull request to update the official plugin with the the fix. I'm so sorry it took this long, but life got in the way

**Comment by microtavor5** [comment]
Ok, I've added an axis aligned bounding box check which I think speeds up the check immensely, so hopefully that will fix the issue, if not Adam had another idea along the same vein that would probably be even faster
